// defaultPermissions.js
export const DEFAULT_PERMISSIONS = {
	member: {
		dashboard: {
			connectNow: false,
			viewUsers: false,
			quickActions: true,
			addPhoneNumber: false,
		},
		chats: {
			type: true,
			view: true,
			chat: false,
			allChats: false,
		},
		contactList: {
			type: true,
			customField: true,
			addContactIndividual: false,
			editContactIndividual: false,
			deleteContactIndividual: false,
			addContactListCSV: false,
			deleteList: false,
			sendBroadcast: true,
			allList: false,
			downloadList: false,
		},
		templates: {
			type: true,
			duplicateTemplate: false,
			editTemplate: false,
			createTemplate: false,
			deleteTemplate: false,
		},
		reports: {
			type: true,
			conversationReports: {
				type: true,
				viewReports: true,
				retargetingUsers: false,
			},
			costReports: false,
		},
		settings: {
			type: true,
			userManagement: {
				type: false,
				addUser: false,
				addPermission: false,
				editPermission: false,
				deletePermission: false,
			},
			activityLogs: true,
			manageTags: {
				type: false,
				delete: false,
				add: false,
				view: false,
			},
			whatsAppAccountDetails: false,
			accountDetails: false,
			payment: false,
		},
	},
	admin: {
		dashboard: {
			connectNow: true,
			viewUsers: false,
			quickActions: true,
			addPhoneNumber: false,
		},
		chats: {
			type: true,
			view: true,
			chat: true,
			allChats: false,
		},
		contactList: {
			type: true,
			customField: true,
			addContactIndividual: true,
			editContactIndividual: false,
			deleteContactIndividual: false,
			addContactListCSV: true,
			deleteList: false,
			sendBroadcast: true,
			allList: false,
			downloadList: false,
		},
		templates: {
			type: true,
			duplicateTemplate: false,
			createTemplate: true,
			editTemplate: false,
			deleteTemplate: true,
		},
		reports: {
			type: true,
			conversationReports: {
				type: true,
				viewReports: true,
				retargetingUsers: true,
			},
			costReports: false,
		},
		settings: {
			type: true,
			userManagement: {
				type: false,
				addUser: false,
				addPermission: false,
				editPermission: false,
				deletePermission: false,
			},
			activityLogs: true,
			manageTags: {
				type: false,
				delete: false,
				add: false,
				view: false,
			},
			whatsAppAccountDetails: false,
			accountDetails: false,
			payment: false,
		},
	},
	owner: {
		dashboard: {
			connectNow: true,
			viewUsers: true,
			quickActions: true,
			addPhoneNumber: true,
		},
		chats: {
			type: true,
			view: true,
			chat: true,
			allChats: true,
		},
		contactList: {
			type: true,
			customField: true,
			addContactIndividual: true,
			editContactIndividual: true,
			deleteContactIndividual: true,
			addContactListCSV: true,
			deleteList: true,
			sendBroadcast: true,
			allList: true,
			downloadList: true,
		},
		templates: {
			type: true,
			duplicateTemplate: true,
			createTemplate: true,
			editTemplate: true,
			deleteTemplate: true,
		},
		reports: {
			type: true,
			conversationReports: {
				type: true,
				viewReports: true,
				retargetingUsers: true,
			},
			costReports: true,
		},
		settings: {
			type: true,
			userManagement: {
				type: true,
				addUser: true,
				addPermission: true,
				editPermission: true,
				deletePermission: true,
			},
			activityLogs: true,
			manageTags: {
				type: true,
				delete: true,
				add: true,
				view: true,
			},
			whatsAppAccountDetails: true,
			accountDetails: true,
			payment: true,
		},
	},
	unAssignedChats: {
		dashboard: {
			connectNow: false,
			viewUsers: false,
			quickActions: false,
			addPhoneNumber: false,
		},
		chats: {
			type: false,
			view: false,
			chat: false,
			allChats: false,
		},
		contactList: {
			type: false,
			customField: false,
			addContactIndividual: false,
			editContactIndividual: false,
			deleteContactIndividual: false,
			addContactListCSV: false,
			deleteList: false,
			sendBroadcast: false,
			allList: false,
			downloadList: false,
		},
		templates: {
			type: false,
			duplicateTemplate: false,
			createTemplate: false,
			editTemplate: false,
			deleteTemplate: false,
		},
		reports: {
			type: false,
			conversationReports: {
				type: false,
				viewReports: false,
				retargetingUsers: false,
			},
			costReports: false,
		},
		settings: {
			type: false,
			userManagement: {
				type: false,
				addUser: false,
				addPermission: false,
				editPermission: false,
				deletePermission: false,
			},
			activityLogs: false,
			manageTags: {
				type: false,
				delete: false,
				add: false,
				view: false,
			},
			whatsAppAccountDetails: false,
			accountDetails: false,
			payment: false,
		},
	},
};
