export const countries = [
	{ name: "Algeria", code: "DZ", flag: "🇩🇿", dialCode: "+213" },
	{ name: "Angola", code: "AO", flag: "🇦🇴", dialCode: "+244" },
	{ name: "Benin", code: "BJ", flag: "🇧🇯", dialCode: "+229" },
	{ name: "Botswana", code: "BW", flag: "🇧🇼", dialCode: "+267" },
	{ name: "Burkina Faso", code: "BF", flag: "🇧🇫", dialCode: "+226" },
	{ name: "Burundi", code: "BI", flag: "🇧🇮", dialCode: "+257" },
	{ name: "Cameroon", code: "CM", flag: "🇨🇲", dialCode: "+237" },
	{ name: "Cape Verde", code: "CV", flag: "🇨🇻", dialCode: "+238" },
	{
		name: "Central African Republic",
		code: "CF",
		flag: "🇨🇫",
		dialCode: "+236",
	},
	{ name: "Chad", code: "TD", flag: "🇹🇩", dialCode: "+235" },
	{ name: "Comoros", code: "KM", flag: "🇰🇲", dialCode: "+269" },
	{ name: "Congo", code: "CG", flag: "🇨🇬", dialCode: "+242" },
	{ name: "DR Congo", code: "CD", flag: "🇨🇩", dialCode: "+243" },
	{ name: "Djibouti", code: "DJ", flag: "🇩🇯", dialCode: "+253" },
	{ name: "Egypt", code: "EG", flag: "🇪🇬", dialCode: "+20" },
	{ name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶", dialCode: "+240" },
	{ name: "Eritrea", code: "ER", flag: "🇪🇷", dialCode: "+291" },
	{ name: "Ethiopia", code: "ET", flag: "🇪🇹", dialCode: "+251" },
	{ name: "Gabon", code: "GA", flag: "🇬🇦", dialCode: "+241" },
	{ name: "Gambia", code: "GM", flag: "🇬🇲", dialCode: "+220" },
	{ name: "Ghana", code: "GH", flag: "🇬🇭", dialCode: "+233" },
	{ name: "Guinea", code: "GN", flag: "🇬🇳", dialCode: "+224" },
	{ name: "Guinea-Bissau", code: "GW", flag: "🇬🇼", dialCode: "+245" },
	{ name: "Ivory Coast", code: "CI", flag: "🇨🇮", dialCode: "+225" },
	{ name: "Kenya", code: "KE", flag: "🇰🇪", dialCode: "+254" },
	{ name: "Lesotho", code: "LS", flag: "🇱🇸", dialCode: "+266" },
	{ name: "Liberia", code: "LR", flag: "🇱🇷", dialCode: "+231" },
	{ name: "Libya", code: "LY", flag: "🇱🇾", dialCode: "+218" },
	{ name: "Madagascar", code: "MG", flag: "🇲🇬", dialCode: "+261" },
	{ name: "Malawi", code: "MW", flag: "🇲🇼", dialCode: "+265" },
	{ name: "Mali", code: "ML", flag: "🇲🇱", dialCode: "+223" },
	{ name: "Mauritania", code: "MR", flag: "🇲🇷", dialCode: "+222" },
	{ name: "Mauritius", code: "MU", flag: "🇲🇺", dialCode: "+230" },
	{ name: "Morocco", code: "MA", flag: "🇲🇦", dialCode: "+212" },
	{ name: "Mozambique", code: "MZ", flag: "🇲🇿", dialCode: "+258" },
	{ name: "Namibia", code: "NA", flag: "🇳🇦", dialCode: "+264" },
	{ name: "Niger", code: "NE", flag: "🇳🇪", dialCode: "+227" },
	{ name: "Nigeria", code: "NG", flag: "🇳🇬", dialCode: "+234" },
	{ name: "Rwanda", code: "RW", flag: "🇷🇼", dialCode: "+250" },
	{ name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹", dialCode: "+239" },
	{ name: "Senegal", code: "SN", flag: "🇸🇳", dialCode: "+221" },
	{ name: "Seychelles", code: "SC", flag: "🇸🇨", dialCode: "+248" },
	{ name: "Sierra Leone", code: "SL", flag: "🇸🇱", dialCode: "+232" },
	{ name: "Somalia", code: "SO", flag: "🇸🇴", dialCode: "+252" },
	{ name: "South Africa", code: "ZA", flag: "🇿🇦", dialCode: "+27" },
	{ name: "South Sudan", code: "SS", flag: "🇸🇸", dialCode: "+211" },
	{ name: "Sudan", code: "SD", flag: "🇸🇩", dialCode: "+249" },
	{ name: "Swaziland", code: "SZ", flag: "🇸🇿", dialCode: "+268" },
	{ name: "Tanzania", code: "TZ", flag: "🇹🇿", dialCode: "+255" },
	{ name: "Togo", code: "TG", flag: "🇹🇬", dialCode: "+228" },
	{ name: "Tunisia", code: "TN", flag: "🇹🇳", dialCode: "+216" },
	{ name: "Uganda", code: "UG", flag: "🇺🇬", dialCode: "+256" },
	{ name: "Zambia", code: "ZM", flag: "🇿🇲", dialCode: "+260" },
	{ name: "Zimbabwe", code: "ZW", flag: "🇿🇼", dialCode: "+263" },
	{ name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬", dialCode: "+1" },
	{ name: "Argentina", code: "AR", flag: "🇦🇷", dialCode: "+54" },
	{ name: "Bahamas", code: "BS", flag: "🇧🇸", dialCode: "+1" },
	{ name: "Barbados", code: "BB", flag: "🇧🇧", dialCode: "+1" },
	{ name: "Belize", code: "BZ", flag: "🇧🇿", dialCode: "+501" },
	{ name: "Bolivia", code: "BO", flag: "🇧🇴", dialCode: "+591" },
	{
		name: "Brazil",
		code: "BR",
		flag: "🇧🇷",
		dialCode: "+55",
		states: [
			{ name: "Acre", code: "AC" },
			{ name: "Alagoas", code: "AL" },
			{ name: "Amapá", code: "AP" },
			{ name: "Amazonas", code: "AM" },
			{ name: "Bahia", code: "BA" },
			{ name: "Ceará", code: "CE" },
			{ name: "Distrito Federal", code: "DF" },
			{ name: "Espírito Santo", code: "ES" },
			{ name: "Goiás", code: "GO" },
			{ name: "Maranhão", code: "MA" },
			{ name: "Mato Grosso", code: "MT" },
			{ name: "Mato Grosso do Sul", code: "MS" },
			{ name: "Minas Gerais", code: "MG" },
			{ name: "Pará", code: "PA" },
			{ name: "Paraíba", code: "PB" },
			{ name: "Paraná", code: "PR" },
			{ name: "Pernambuco", code: "PE" },
			{ name: "Piauí", code: "PI" },
			{ name: "Rio de Janeiro", code: "RJ" },
			{ name: "Rio Grande do Norte", code: "RN" },
			{ name: "Rio Grande do Sul", code: "RS" },
			{ name: "Rondônia", code: "RO" },
			{ name: "Roraima", code: "RR" },
			{ name: "Santa Catarina", code: "SC" },
			{ name: "São Paulo", code: "SP" },
			{ name: "Sergipe", code: "SE" },
			{ name: "Tocantins", code: "TO" },
		],
	},
	{
		name: "Canada",
		code: "CA",
		flag: "🇨🇦",
		dialCode: "+1",
		states: [
			{ name: "Alberta", code: "AB" },
			{ name: "British Columbia", code: "BC" },
			{ name: "Manitoba", code: "MB" },
			{ name: "New Brunswick", code: "NB" },
			{ name: "Newfoundland and Labrador", code: "NL" },
			{ name: "Nova Scotia", code: "NS" },
			{ name: "Ontario", code: "ON" },
			{ name: "Prince Edward Island", code: "PE" },
			{ name: "Quebec", code: "QC" },
			{ name: "Saskatchewan", code: "SK" },
			// Territories
			{ name: "Northwest Territories", code: "NT" },
			{ name: "Nunavut", code: "NU" },
			{ name: "Yukon", code: "YT" },
		],
	},
	{ name: "Chile", code: "CL", flag: "🇨🇱", dialCode: "+56" },
	{ name: "Colombia", code: "CO", flag: "🇨🇴", dialCode: "+57" },
	{ name: "Costa Rica", code: "CR", flag: "🇨🇷", dialCode: "+506" },
	{ name: "Cuba", code: "CU", flag: "🇨🇺", dialCode: "+53" },
	{ name: "Dominica", code: "DM", flag: "🇩🇲", dialCode: "+1" },
	{ name: "Dominican Republic", code: "DO", flag: "🇩🇴", dialCode: "+1" },
	{ name: "Ecuador", code: "EC", flag: "🇪🇨", dialCode: "+593" },
	{ name: "El Salvador", code: "SV", flag: "🇸🇻", dialCode: "+503" },
	{ name: "Grenada", code: "GD", flag: "🇬🇩", dialCode: "+1" },
	{ name: "Guatemala", code: "GT", flag: "🇬🇹", dialCode: "+502" },
	{ name: "Guyana", code: "GY", flag: "🇬🇾", dialCode: "+592" },
	{ name: "Haiti", code: "HT", flag: "🇭🇹", dialCode: "+509" },
	{ name: "Honduras", code: "HN", flag: "🇭🇳", dialCode: "+504" },
	{ name: "Jamaica", code: "JM", flag: "🇯🇲", dialCode: "+1" },
	{
		name: "Mexico",
		code: "MX",
		flag: "🇲🇽",
		dialCode: "+52",
		states: [
			{ name: "Aguascalientes", code: "AG" },
			{ name: "Baja California", code: "BC" },
			{ name: "Baja California Sur", code: "BS" },
			{ name: "Campeche", code: "CM" },
			{ name: "Chiapas", code: "CS" },
			{ name: "Chihuahua", code: "CH" },
			{ name: "Coahuila", code: "CO" },
			{ name: "Colima", code: "CL" },
			{ name: "Durango", code: "DG" },
			{ name: "Guanajuato", code: "GT" },
			{ name: "Guerrero", code: "GR" },
			{ name: "Hidalgo", code: "HG" },
			{ name: "Jalisco", code: "JA" },
			{ name: "México", code: "ME" },
			{ name: "Mexico City", code: "DF" },
			{ name: "Michoacán", code: "MI" },
			{ name: "Morelos", code: "MO" },
			{ name: "Nayarit", code: "NA" },
			{ name: "Nuevo León", code: "NL" },
			{ name: "Oaxaca", code: "OA" },
			{ name: "Puebla", code: "PU" },
			{ name: "Querétaro", code: "QE" },
			{ name: "Quintana Roo", code: "QR" },
			{ name: "San Luis Potosí", code: "SL" },
			{ name: "Sinaloa", code: "SI" },
			{ name: "Sonora", code: "SO" },
			{ name: "Tabasco", code: "TB" },
			{ name: "Tamaulipas", code: "TM" },
			{ name: "Tlaxcala", code: "TL" },
			{ name: "Veracruz", code: "VE" },
			{ name: "Yucatán", code: "YU" },
			{ name: "Zacatecas", code: "ZA" },
		],
	},
	{ name: "Nicaragua", code: "NI", flag: "🇳🇮", dialCode: "+505" },
	{ name: "Panama", code: "PA", flag: "🇵🇦", dialCode: "+507" },
	{ name: "Paraguay", code: "PY", flag: "🇵🇾", dialCode: "+595" },
	{ name: "Peru", code: "PE", flag: "🇵🇪", dialCode: "+51" },
	{ name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳", dialCode: "+1" },
	{ name: "Saint Lucia", code: "LC", flag: "🇱🇨", dialCode: "+1" },
	{
		name: "Saint Vincent and the Grenadines",
		code: "VC",
		flag: "🇻🇨",
		dialCode: "+1",
	},
	{ name: "Suriname", code: "SR", flag: "🇸🇷", dialCode: "+597" },
	{ name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹", dialCode: "+1" },
	{
		name: "United States",
		code: "US",
		flag: "🇺🇸",
		dialCode: "+1",
		states: [
			{ name: "Alabama", code: "AL" },
			{ name: "Alaska", code: "AK" },
			{ name: "Arizona", code: "AZ" },
			{ name: "Arkansas", code: "AR" },
			{ name: "California", code: "CA" },
			{ name: "Colorado", code: "CO" },
			{ name: "Connecticut", code: "CT" },
			{ name: "Delaware", code: "DE" },
			{ name: "Florida", code: "FL" },
			{ name: "Georgia", code: "GA" },
			{ name: "Hawaii", code: "HI" },
			{ name: "Idaho", code: "ID" },
			{ name: "Illinois", code: "IL" },
			{ name: "Indiana", code: "IN" },
			{ name: "Iowa", code: "IA" },
			{ name: "Kansas", code: "KS" },
			{ name: "Kentucky", code: "KY" },
			{ name: "Louisiana", code: "LA" },
			{ name: "Maine", code: "ME" },
			{ name: "Maryland", code: "MD" },
			{ name: "Massachusetts", code: "MA" },
			{ name: "Michigan", code: "MI" },
			{ name: "Minnesota", code: "MN" },
			{ name: "Mississippi", code: "MS" },
			{ name: "Missouri", code: "MO" },
			{ name: "Montana", code: "MT" },
			{ name: "Nebraska", code: "NE" },
			{ name: "Nevada", code: "NV" },
			{ name: "New Hampshire", code: "NH" },
			{ name: "New Jersey", code: "NJ" },
			{ name: "New Mexico", code: "NM" },
			{ name: "New York", code: "NY" },
			{ name: "North Carolina", code: "NC" },
			{ name: "North Dakota", code: "ND" },
			{ name: "Ohio", code: "OH" },
			{ name: "Oklahoma", code: "OK" },
			{ name: "Oregon", code: "OR" },
			{ name: "Pennsylvania", code: "PA" },
			{ name: "Rhode Island", code: "RI" },
			{ name: "South Carolina", code: "SC" },
			{ name: "South Dakota", code: "SD" },
			{ name: "Tennessee", code: "TN" },
			{ name: "Texas", code: "TX" },
			{ name: "Utah", code: "UT" },
			{ name: "Vermont", code: "VT" },
			{ name: "Virginia", code: "VA" },
			{ name: "Washington", code: "WA" },
			{ name: "West Virginia", code: "WV" },
			{ name: "Wisconsin", code: "WI" },
			{ name: "Wyoming", code: "WY" },
			// Territories
			{ name: "American Samoa", code: "AS" },
			{ name: "District of Columbia", code: "DC" },
			{ name: "Guam", code: "GU" },
			{ name: "Northern Mariana Islands", code: "MP" },
			{ name: "Puerto Rico", code: "PR" },
			{ name: "U.S. Virgin Islands", code: "VI" },
		],
	},
	{ name: "Uruguay", code: "UY", flag: "🇺🇾", dialCode: "+598" },
	{ name: "Venezuela", code: "VE", flag: "🇻🇪", dialCode: "+58" },
	{ name: "Afghanistan", code: "AF", flag: "🇦🇫", dialCode: "+93" },
	{ name: "Armenia", code: "AM", flag: "🇦🇲", dialCode: "+374" },
	{ name: "Azerbaijan", code: "AZ", flag: "🇦🇿", dialCode: "+994" },
	{ name: "Bahrain", code: "BH", flag: "🇧🇭", dialCode: "+973" },
	{ name: "Bangladesh", code: "BD", flag: "🇧🇩", dialCode: "+880" },
	{ name: "Bhutan", code: "BT", flag: "🇧🇹", dialCode: "+975" },
	{ name: "Brunei", code: "BN", flag: "🇧🇳", dialCode: "+673" },
	{ name: "Cambodia", code: "KH", flag: "🇰🇭", dialCode: "+855" },
	{
		name: "China",
		code: "CN",
		flag: "🇨🇳",
		dialCode: "+86",
		states: [
			{ name: "Anhui", code: "AH" },
			{ name: "Beijing", code: "BJ" },
			{ name: "Chongqing", code: "CQ" },
			{ name: "Fujian", code: "FJ" },
			{ name: "Gansu", code: "GS" },
			{ name: "Guangdong", code: "GD" },
			{ name: "Guangxi", code: "GX" },
			{ name: "Guizhou", code: "GZ" },
			{ name: "Hainan", code: "HI" },
			{ name: "Hebei", code: "HE" },
			{ name: "Heilongjiang", code: "HL" },
			{ name: "Henan", code: "HA" },
			{ name: "Hubei", code: "HB" },
			{ name: "Hunan", code: "HN" },
			{ name: "Inner Mongolia", code: "NM" },
			{ name: "Jiangsu", code: "JS" },
			{ name: "Jiangxi", code: "JX" },
			{ name: "Jilin", code: "JL" },
			{ name: "Liaoning", code: "LN" },
			{ name: "Ningxia", code: "NX" },
			{ name: "Qinghai", code: "QH" },
			{ name: "Shaanxi", code: "SN" },
			{ name: "Shandong", code: "SD" },
			{ name: "Shanghai", code: "SH" },
			{ name: "Shanxi", code: "SX" },
			{ name: "Sichuan", code: "SC" },
			{ name: "Tianjin", code: "TJ" },
			{ name: "Tibet", code: "XZ" },
			{ name: "Xinjiang", code: "XJ" },
			{ name: "Yunnan", code: "YN" },
			{ name: "Zhejiang", code: "ZJ" },
			{ name: "Hong Kong", code: "HK" },
			{ name: "Macau", code: "MO" },
		],
	},
	{ name: "Cyprus", code: "CY", flag: "🇨🇾", dialCode: "+357" },
	{ name: "Georgia", code: "GE", flag: "🇬🇪", dialCode: "+995" },
	{ name: "Hong Kong", code: "HK", flag: "🇭🇰", dialCode: "+852" },
	{
		name: "India",
		code: "IN",
		flag: "🇮🇳",
		dialCode: "+91",
		states: [
			{ name: "Andhra Pradesh", code: "AP" },
			{ name: "Arunachal Pradesh", code: "AR" },
			{ name: "Assam", code: "AS" },
			{ name: "Bihar", code: "BR" },
			{ name: "Chhattisgarh", code: "CT" },
			{ name: "Goa", code: "GA" },
			{ name: "Gujarat", code: "GJ" },
			{ name: "Haryana", code: "HR" },
			{ name: "Himachal Pradesh", code: "HP" },
			{ name: "Jharkhand", code: "JH" },
			{ name: "Karnataka", code: "KA" },
			{ name: "Kerala", code: "KL" },
			{ name: "Madhya Pradesh", code: "MP" },
			{ name: "Maharashtra", code: "MH" },
			{ name: "Manipur", code: "MN" },
			{ name: "Meghalaya", code: "ML" },
			{ name: "Mizoram", code: "MZ" },
			{ name: "Nagaland", code: "NL" },
			{ name: "Odisha", code: "OR" },
			{ name: "Punjab", code: "PB" },
			{ name: "Rajasthan", code: "RJ" },
			{ name: "Sikkim", code: "SK" },
			{ name: "Tamil Nadu", code: "TN" },
			{ name: "Telangana", code: "TG" },
			{ name: "Tripura", code: "TR" },
			{ name: "Uttar Pradesh", code: "UP" },
			{ name: "Uttarakhand", code: "UT" },
			{ name: "West Bengal", code: "WB" },
			// Union Territories
			{ name: "Andaman and Nicobar Islands", code: "AN" },
			{ name: "Chandigarh", code: "CH" },
			{ name: "Dadra and Nagar Haveli and Daman and Diu", code: "DH" },
			{ name: "Delhi", code: "DL" },
			{ name: "Jammu and Kashmir", code: "JK" },
			{ name: "Ladakh", code: "LA" },
			{ name: "Lakshadweep", code: "LD" },
			{ name: "Puducherry", code: "PY" },
		],
	},
	{ name: "Indonesia", code: "ID", flag: "🇮🇩", dialCode: "+62" },
	{ name: "Iran", code: "IR", flag: "🇮🇷", dialCode: "+98" },
	{ name: "Iraq", code: "IQ", flag: "🇮🇶", dialCode: "+964" },
	{ name: "Israel", code: "IL", flag: "🇮🇱", dialCode: "+972" },
	{ name: "Japan", code: "JP", flag: "🇯🇵", dialCode: "+81" },
	{ name: "Jordan", code: "JO", flag: "🇯🇴", dialCode: "+962" },
	{ name: "Kazakhstan", code: "KZ", flag: "🇰🇿", dialCode: "+7" },
	{ name: "Kuwait", code: "KW", flag: "🇰🇼", dialCode: "+965" },
	{ name: "Kyrgyzstan", code: "KG", flag: "🇰🇬", dialCode: "+996" },
	{ name: "Laos", code: "LA", flag: "🇱🇦", dialCode: "+856" },
	{ name: "Lebanon", code: "LB", flag: "🇱🇧", dialCode: "+961" },
	{ name: "Macau", code: "MO", flag: "🇲🇴", dialCode: "+853" },
	{ name: "Malaysia", code: "MY", flag: "🇲🇾", dialCode: "+60" },
	{ name: "Maldives", code: "MV", flag: "🇲🇻", dialCode: "+960" },
	{ name: "Mongolia", code: "MN", flag: "🇲🇳", dialCode: "+976" },
	{ name: "Myanmar", code: "MM", flag: "🇲🇲", dialCode: "+95" },
	{ name: "Nepal", code: "NP", flag: "🇳🇵", dialCode: "+977" },
	{ name: "North Korea", code: "KP", flag: "🇰🇵", dialCode: "+850" },
	{ name: "Oman", code: "OM", flag: "🇴🇲", dialCode: "+968" },
	{ name: "Pakistan", code: "PK", flag: "🇵🇰", dialCode: "+92" },
	{ name: "Palestine", code: "PS", flag: "🇵🇸", dialCode: "+970" },
	{ name: "Philippines", code: "PH", flag: "🇵🇭", dialCode: "+63" },
	{ name: "Qatar", code: "QA", flag: "🇶🇦", dialCode: "+974" },
	{ name: "Saudi Arabia", code: "SA", flag: "🇸🇦", dialCode: "+966" },
	{ name: "Singapore", code: "SG", flag: "🇸🇬", dialCode: "+65" },
	{ name: "South Korea", code: "KR", flag: "🇰🇷", dialCode: "+82" },
	{ name: "Sri Lanka", code: "LK", flag: "🇱🇰", dialCode: "+94" },
	{ name: "Syria", code: "SY", flag: "🇸🇾", dialCode: "+963" },
	{ name: "Taiwan", code: "TW", flag: "🇹🇼", dialCode: "+886" },
	{ name: "Tajikistan", code: "TJ", flag: "🇹🇯", dialCode: "+992" },
	{ name: "Thailand", code: "TH", flag: "🇹🇭", dialCode: "+66" },
	{ name: "Timor-Leste", code: "TL", flag: "🇹🇱", dialCode: "+670" },
	{ name: "Turkey", code: "TR", flag: "🇹🇷", dialCode: "+90" },
	{ name: "Turkmenistan", code: "TM", flag: "🇹🇲", dialCode: "+993" },
	{ name: "United Arab Emirates", code: "AE", flag: "🇦🇪", dialCode: "+971" },
	{ name: "Uzbekistan", code: "UZ", flag: "🇺🇿", dialCode: "+998" },
	{ name: "Vietnam", code: "VN", flag: "🇻🇳", dialCode: "+84" },
	{ name: "Yemen", code: "YE", flag: "🇾🇪", dialCode: "+967" },
	{ name: "Albania", code: "AL", flag: "🇦🇱", dialCode: "+355" },
	{ name: "Andorra", code: "AD", flag: "🇦🇩", dialCode: "+376" },
	{ name: "Austria", code: "AT", flag: "🇦🇹", dialCode: "+43" },
	{ name: "Belarus", code: "BY", flag: "🇧🇾", dialCode: "+375" },
	{ name: "Belgium", code: "BE", flag: "🇧🇪", dialCode: "+32" },
	{
		name: "Bosnia and Herzegovina",
		code: "BA",
		flag: "🇧🇦",
		dialCode: "+387",
	},
	{ name: "Bulgaria", code: "BG", flag: "🇧🇬", dialCode: "+359" },
	{ name: "Croatia", code: "HR", flag: "🇭🇷", dialCode: "+385" },
	{ name: "Czech Republic", code: "CZ", flag: "🇨🇿", dialCode: "+420" },
	{ name: "Denmark", code: "DK", flag: "🇩🇰", dialCode: "+45" },
	{ name: "Estonia", code: "EE", flag: "🇪🇪", dialCode: "+372" },
	{ name: "Finland", code: "FI", flag: "🇫🇮", dialCode: "+358" },
	{ name: "France", code: "FR", flag: "🇫🇷", dialCode: "+33" },
	{
		name: "Germany",
		code: "DE",
		flag: "🇩🇪",
		dialCode: "+49",
		states: [
			{ name: "Baden-Württemberg", code: "BW" },
			{ name: "Bavaria", code: "BY" },
			{ name: "Berlin", code: "BE" },
			{ name: "Brandenburg", code: "BB" },
			{ name: "Bremen", code: "HB" },
			{ name: "Hamburg", code: "HH" },
			{ name: "Hesse", code: "HE" },
			{ name: "Lower Saxony", code: "NI" },
			{ name: "Mecklenburg-Western Pomerania", code: "MV" },
			{ name: "North Rhine-Westphalia", code: "NW" },
			{ name: "Rhineland-Palatinate", code: "RP" },
			{ name: "Saarland", code: "SL" },
			{ name: "Saxony", code: "SN" },
			{ name: "Saxony-Anhalt", code: "ST" },
			{ name: "Schleswig-Holstein", code: "SH" },
			{ name: "Thuringia", code: "TH" },
		],
	},
	{ name: "Greece", code: "GR", flag: "🇬🇷", dialCode: "+30" },
	{ name: "Hungary", code: "HU", flag: "🇭🇺", dialCode: "+36" },
	{ name: "Iceland", code: "IS", flag: "🇮🇸", dialCode: "+354" },
	{ name: "Ireland", code: "IE", flag: "🇮🇪", dialCode: "+353" },
	{ name: "Italy", code: "IT", flag: "🇮🇹", dialCode: "+39" },
	{ name: "Latvia", code: "LV", flag: "🇱🇻", dialCode: "+371" },
	{ name: "Liechtenstein", code: "LI", flag: "🇱🇮", dialCode: "+423" },
	{ name: "Lithuania", code: "LT", flag: "🇱🇹", dialCode: "+370" },
	{ name: "Luxembourg", code: "LU", flag: "🇱🇺", dialCode: "+352" },
	{ name: "Malta", code: "MT", flag: "🇲🇹", dialCode: "+356" },
	{ name: "Moldova", code: "MD", flag: "🇲🇩", dialCode: "+373" },
	{ name: "Monaco", code: "MC", flag: "🇲🇨", dialCode: "+377" },
	{ name: "Montenegro", code: "ME", flag: "🇲🇪", dialCode: "+382" },
	{ name: "Netherlands", code: "NL", flag: "🇳🇱", dialCode: "+31" },
	{ name: "North Macedonia", code: "MK", flag: "🇲🇰", dialCode: "+389" },
	{ name: "Norway", code: "NO", flag: "🇳🇴", dialCode: "+47" },
	{ name: "Poland", code: "PL", flag: "🇵🇱", dialCode: "+48" },
	{ name: "Portugal", code: "PT", flag: "🇵🇹", dialCode: "+351" },
	{ name: "Romania", code: "RO", flag: "🇷🇴", dialCode: "+40" },
	{
		name: "Russia",
		code: "RU",
		flag: "🇷🇺",
		dialCode: "+7",
		states: [
			// Federal Cities
			{ name: "Moscow", code: "MOW" },
			{ name: "Saint Petersburg", code: "SPE" },
			{ name: "Sevastopol", code: "SEV" },
			// Republics
			{ name: "Republic of Adygea", code: "AD" },
			{ name: "Republic of Altai", code: "AL" },
			{ name: "Republic of Bashkortostan", code: "BA" },
			{ name: "Republic of Buryatia", code: "BU" },
			{ name: "Chechen Republic", code: "CE" },
			{ name: "Chuvash Republic", code: "CU" },
			{ name: "Republic of Dagestan", code: "DA" },
			{ name: "Republic of Ingushetia", code: "IN" },
			{ name: "Kabardino-Balkar Republic", code: "KB" },
			{ name: "Republic of Kalmykia", code: "KL" },
			{ name: "Karachay-Cherkess Republic", code: "KC" },
			{ name: "Republic of Karelia", code: "KR" },
			{ name: "Republic of Khakassia", code: "KK" },
			{ name: "Republic of Komi", code: "KO" },
			{ name: "Mari El Republic", code: "ME" },
			{ name: "Republic of Mordovia", code: "MO" },
			{ name: "Republic of North Ossetia-Alania", code: "SE" },
			{ name: "Republic of Tatarstan", code: "TA" },
			{ name: "Republic of Tuva", code: "TY" },
			{ name: "Udmurt Republic", code: "UD" },
			// Krais
			{ name: "Altai Krai", code: "ALT" },
			{ name: "Kamchatka Krai", code: "KAM" },
			{ name: "Khabarovsk Krai", code: "KHA" },
			{ name: "Krasnodar Krai", code: "KDA" },
			{ name: "Krasnoyarsk Krai", code: "KYA" },
			{ name: "Perm Krai", code: "PER" },
			{ name: "Primorsky Krai", code: "PRI" },
			{ name: "Stavropol Krai", code: "STA" },
			{ name: "Zabaykalsky Krai", code: "ZAB" },
		],
	},
	{ name: "San Marino", code: "SM", flag: "🇸🇲", dialCode: "+378" },
	{ name: "Serbia", code: "RS", flag: "🇷🇸", dialCode: "+381" },
	{ name: "Slovakia", code: "SK", flag: "🇸🇰", dialCode: "+421" },
	{ name: "Slovenia", code: "SI", flag: "🇸🇮", dialCode: "+386" },
	{ name: "Spain", code: "ES", flag: "🇪🇸", dialCode: "+34" },
	{ name: "Sweden", code: "SE", flag: "🇸🇪", dialCode: "+46" },
	{ name: "Switzerland", code: "CH", flag: "🇨🇭", dialCode: "+41" },
	{ name: "Ukraine", code: "UA", flag: "🇺🇦", dialCode: "+380" },
	{ name: "United Kingdom", code: "GB", flag: "🇬🇧", dialCode: "+44" },
	{ name: "Vatican City", code: "VA", flag: "🇻🇦", dialCode: "+379" },
	{
		name: "Australia",
		code: "AU",
		flag: "🇦🇺",
		dialCode: "+61",
		states: [
			{ name: "Australian Capital Territory", code: "ACT" },
			{ name: "New South Wales", code: "NSW" },
			{ name: "Northern Territory", code: "NT" },
			{ name: "Queensland", code: "QLD" },
			{ name: "South Australia", code: "SA" },
			{ name: "Tasmania", code: "TAS" },
			{ name: "Victoria", code: "VIC" },
			{ name: "Western Australia", code: "WA" },
		],
	},
	{ name: "Fiji", code: "FJ", flag: "🇫🇯", dialCode: "+679" },
	{ name: "Kiribati", code: "KI", flag: "🇰🇮", dialCode: "+686" },
	{ name: "Marshall Islands", code: "MH", flag: "🇲🇭", dialCode: "+692" },
	{ name: "Micronesia", code: "FM", flag: "🇫🇲", dialCode: "+691" },
	{ name: "Nauru", code: "NR", flag: "🇳🇷", dialCode: "+674" },
	{ name: "New Zealand", code: "NZ", flag: "🇳🇿", dialCode: "+64" },
	{ name: "Palau", code: "PW", flag: "🇵🇼", dialCode: "+680" },
	{ name: "Papua New Guinea", code: "PG", flag: "🇵🇬", dialCode: "+675" },
	{ name: "Samoa", code: "WS", flag: "🇼🇸", dialCode: "+685" },
	{ name: "Solomon Islands", code: "SB", flag: "🇸🇧", dialCode: "+677" },
	{ name: "Tonga", code: "TO", flag: "🇹🇴", dialCode: "+676" },
	{ name: "Tuvalu", code: "TV", flag: "🇹🇻", dialCode: "+688" },
	{ name: "Vanuatu", code: "VU", flag: "🇻🇺", dialCode: "+678" },
];

export const size = [
	"1-10",
	"11-20",
	"21-50",
	"51-200",
	"201-1,000",
	"More than 1,000",
];

export const industryCategory = [
	"Ecommerce",
	"Education",
	"Automotive",
	"IT Services",
	"Real Estate",
	"SAAS/Apps",
	"Gaming",
	"Entertainment",
	"Finance and Banking",
	"Medical and Health",
	"Hotel and Lodging",
	"Beauty, Spa and Salon",
	"Clothing and Apparel",
	"Event Planning and Service",
	"Food and Grocery",
	"Professional Services",
	"Public Service",
	"Arts & Entertainment",
	"Business & Industrial",
	"Electronics",
	"Food & Beverages",
	"Hardware",
	"Health & Beauty",
	"Home & Garden",
	"HR Consultants",
	"Media",
	"NGO",
	"Real Estate",
	"Religious & Ceremonial",
	"Sofware",
	"Sporting Goods",
	"Tax Consultants",
	"Tours & Travel",
	"Vehicles & Parts",
	"Other",
];

export const roles = [
	"Founder",
	"Marketer",
	"Sales / Business Development",
	"Customer Support",
	"Developer/Product Manager",
	"Others",
];

export const languages = [
	"Afrikaans",
	"Albanian",
	"Amharic",
	"Arabic",
	"Armenian",
	"Assamese",
	"Aymara",
	"Azerbaijani",
	"Bambara",
	"Basque",
	"Belarusian",
	"Bengali",
	"Bhojpuri",
	"Bosnian",
	"Bulgarian",
	"Catalan",
	"Cebuano",
	"Chinese (Simplified)",
	"Chinese (Traditional)",
	"Corsican",
	"Croatian",
	"Czech",
	"Danish",
	"Dhivehi",
	"Dogri",
	"Dutch",
	"English",
	"Esperanto",
	"Estonian",
	"Ewe",
	"Filipino",
	"Finnish",
	"French",
	"Frisian",
	"Galician",
	"Georgian",
	"German",
	"Greek",
	"Guarani",
	"Gujarati",
	"Haitian Creole",
	"Hausa",
	"Hawaiian",
	"Hebrew",
	"Hindi",
	"Hmong",
	"Hungarian",
	"Icelandic",
	"Igbo",
	"Ilocano",
	"Indonesian",
	"Irish",
	"Italian",
	"Japanese",
	"Javanese",
	"Kannada",
	"Kazakh",
	"Khmer",
	"Kinyarwanda",
	"Konkani",
	"Korean",
	"Krio",
	"Kurdish (Kurmanji)",
	"Kurdish (Sorani)",
	"Kyrgyz",
	"Lao",
	"Latin",
	"Latvian",
	"Lingala",
	"Lithuanian",
	"Luxembourgish",
	"Macedonian",
	"Maithili",
	"Malagasy",
	"Malay",
	"Malayalam",
	"Maltese",
	"Maori",
	"Marathi",
	"Meiteilon (Manipuri)",
	"Mizo",
	"Mongolian",
	"Myanmar (Burmese)",
	"Nepali",
	"Norwegian",
	"Nyanja (Chichewa)",
	"Odia (Oriya)",
	"Oromo",
	"Pashto",
	"Persian",
	"Polish",
	"Portuguese",
	"Punjabi",
	"Quechua",
	"Romanian",
	"Russian",
	"Samoan",
	"Sanskrit",
	"Scots Gaelic",
	"Serbian",
	"Sesotho",
	"Shona",
	"Sindhi",
	"Sinhala",
	"Slovak",
	"Slovenian",
	"Somali",
	"Spanish",
	"Sundanese",
	"Swahili",
	"Swedish",
	"Tajik",
	"Tamil",
	"Tatar",
	"Telugu",
	"Thai",
	"Tigrinya",
	"Tsonga",
	"Turkish",
	"Turkmen",
	"Twi (Akan)",
	"Ukrainian",
	"Urdu",
	"Uyghur",
	"Uzbek",
	"Vietnamese",
	"Welsh",
	"Xhosa",
	"Yiddish",
	"Yoruba",
	"Zulu",
];

export const languagesCode = [
	{ language: "Afrikaans", code: "af" },
	{ language: "Albanian", code: "sq" },
	{ language: "Arabic", code: "ar" },
	{ language: "Azerbaijani", code: "az" },
	{ language: "Bengali", code: "bn" },
	{ language: "Bulgarian", code: "bg" },
	{ language: "Catalan", code: "ca" },
	{ language: "Chinese (Simplified)", code: "zh_CN" },
	{ language: "Chinese (Hong Kong)", code: "zh_HK" },
	{ language: "Chinese (Taiwan)", code: "zh_TW" },
	{ language: "Croatian", code: "hr" },
	{ language: "Czech", code: "cs" },
	{ language: "Danish", code: "da" },
	{ language: "Dutch", code: "nl" },
	{ language: "English", code: "en" },
	{ language: "English (UK)", code: "en_GB" },
	{ language: "English (US)", code: "en_US" },
	{ language: "Estonian", code: "et" },
	{ language: "Filipino", code: "fil" },
	{ language: "Finnish", code: "fi" },
	{ language: "French", code: "fr" },
	{ language: "Georgian", code: "ka" },
	{ language: "German", code: "de" },
	{ language: "Greek", code: "el" },
	{ language: "Gujarati", code: "gu" },
	{ language: "Hausa", code: "ha" },
	{ language: "Hebrew", code: "he" },
	{ language: "Hindi", code: "hi" },
	{ language: "Hungarian", code: "hu" },
	{ language: "Indonesian", code: "id" },
	{ language: "Irish", code: "ga" },
	{ language: "Italian", code: "it" },
	{ language: "Japanese", code: "ja" },
	{ language: "Kannada", code: "kn" },
	{ language: "Kazakh", code: "kk" },
	{ language: "Kinyarwanda", code: "rw_RW" },
	{ language: "Korean", code: "ko" },
	{ language: "Kyrgyz (Kyrgyzstan)", code: "ky_KG" },
	{ language: "Lao", code: "lo" },
	{ language: "Latvian", code: "lv" },
	{ language: "Lithuanian", code: "lt" },
	{ language: "Macedonian", code: "mk" },
	{ language: "Malay", code: "ms" },
	{ language: "Malayalam", code: "ml" },
	{ language: "Marathi", code: "mr" },
	{ language: "Norwegian", code: "nb" },
	{ language: "Persian", code: "fa" },
	{ language: "Polish", code: "pl" },
	{ language: "Portuguese (Brazil)", code: "pt_BR" },
	{ language: "Portuguese (Portugal)", code: "pt_PT" },
	{ language: "Punjabi", code: "pa" },
	{ language: "Romanian", code: "ro" },
	{ language: "Russian", code: "ru" },
	{ language: "Serbian", code: "sr" },
	{ language: "Slovak", code: "sk" },
	{ language: "Slovenian", code: "sl" },
	{ language: "Spanish", code: "es" },
	{ language: "Spanish (Argentina)", code: "es_AR" },
	{ language: "Spanish (Mexico)", code: "es_MX" },
	{ language: "Spanish (Spain)", code: "es_ES" },
	{ language: "Swahili", code: "sw" },
	{ language: "Swedish", code: "sv" },
	{ language: "Tamil", code: "ta" },
	{ language: "Telugu", code: "te" },
	{ language: "Thai", code: "th" },
	{ language: "Turkish", code: "tr" },
	{ language: "Ukrainian", code: "uk" },
	{ language: "Urdu", code: "ur" },
	{ language: "Uzbek", code: "uz" },
	{ language: "Vietnamese", code: "vi" },
	{ language: "Zulu", code: "zu" },
];

export const help = [
	{
		a: "https://whizardapi.com/lets-apply-for-whatsapp-business-api-with-whizard/",
		title: "How to apply for Whatsapp Business API?",
		description:
			"Discover how to apply for Official WhatsApp Business API for FREE with Whizard.",
	},
	{
		a: "https://whizardapi.com/how-to-verify-facebook-business/",
		title: "Verify Facebook Business Manager Account",
		description:
			"Click here to see how to Verify a Facebook Business Manager (FBM) Account for WhatsApp Business API with Whizard API",
	},
	{
		a: "https://whizardapi.com/what-if-the-facebook-start-verification-button-is-greyed-out-or-doesnt-appear/",
		title: "Enable 'Start Verification' Button",
		description:
			"What If the Facebook 'Start Verification' Button Is Greyed Out or Doesn’t Appear?",
	},
];

export const verticalCategories = {
	ALCOHOL: "Alcoholic Beverages",
	APPAREL: "Clothing and Apparel",
	AUTO: "Automotive",
	BEAUTY: "Beauty, Spa and Salon",
	EDU: "Education",
	ENTERTAIN: "Entertainment",
	EVENT_PLAN: "Event Planning and Service",
	FINANCE: "Finance and Banking",
	GOVT: "Public Service",
	GROCERY: "Food and Grocery",
	HEALTH: "Medical and Health",
	HOTEL: "Hotel and Lodging",
	NONPROFIT: "Non-profit",
	ONLINE_GAMBLING: "Online Gambling & Gaming",
	OTC_DRUGS: "Over-the-Counter Drugs",
	OTHER: "Other",
	PHYSICAL_GAMBLING: "Non-Online Gambling & Gaming (E.g. Brick and mortar)",
	PROF_SERVICES: "Professional Services",
	RESTAURANT: "Restaurant",
	RETAIL: "Shopping and Retail",
	TRAVEL: "Travel and Transportation",
};
  